Add spinner drawing
getyourway/flutter_gyw pull request #40
Opened 2023-12-18 13:25 UTC by roscale

Add SpinnerDrawing that will display an animated spinner on the screen.

The parameters of this drawing are:

- image: The filename of the SVG image to be displayed.
- left: The horizontal offset (from the left).
- top: The vertical offset (from the top).
- color: The color of the spinner.
- scale: The spinner scale.
- animationTimingFunction: The animation timing function to use, one of: linear, ease, ease-in, ease-out.
- spinsPerSecond: The number of spins per second.

2023-12-18 13:33 UTC, roscale commented
@TheToto42 

How should I handle custom spinners? I know we've already had this problem with `IconDrawing` and we made another constructor for custom icons, but I dislike that solution because we have to have 2 nullable fields (an icon, or a custom filename) and keep track of which one is non-null.

I was thinking that we should not couple SpinnerDrawing with GYWIcon, and the constructor can just receive the filename as a string. The user could then call `SpinnerDrawing(`GYWIcon.spinner_1.filename`, ...)` or something like that, and if it's a custom icon, just specify the filename of the custom icon without using `GYWIcon`.

2023-12-19 09:49 UTC, TheToto42 requested changes

2023-12-19 09:49 UTC, TheToto42 commented on README.md
> +  image: "spinner_1.svg",
```suggestion
```

2023-12-20 09:34 UTC, TheToto42 approved these changes

2023-12-20 09:34 UTC, merged