Annotate some symbols with `@internal`
getyourway/flutter_gyw pull request #85
Opened 2024-10-07 13:27 UTC by roscale

Attempt to make some symbols package-private by triggering a lint warning if a user references these. This annotation does not enforce anything, but it makes it harder to reference symbols that should only be used by `flutter_gyw`.

2024-10-07 13:32 UTC, roscale commented
The FlutterBluePlus change only affects iOS. I have no way to test this so I hope it works.

2024-10-07 15:06 UTC, TheToto42 requested changes

2024-10-07 15:06 UTC, TheToto42 commented on CHANGELOG.md
> +* [IMP] Annotate `GYWBtDevice.fbDevice` and `GYWBtDevice.findCharacteristic` with `@internal`
```suggestion
## 2.0.4
* [IMP] Annotate `GYWBtDevice.fbDevice` and `GYWBtDevice.findCharacteristic` with `@internal`

## 2.0.3
```
Can you also upgrade the version in the pubspec.yaml file pls

2024-10-08 09:05 UTC, TheToto42 commented
@roscale Did you see my comment ?

2024-10-08 09:15 UTC, roscale commented
No, I missed it.

2024-10-08 09:32 UTC, merged